parameters:
- name: serviceName
  type: string

- name: env
  type: object
  default:
  - DEV

- name: scriptFiles
  type: object
  default:
    DEV: 'docker-swarm.sh'

- name: agentPools
  type: object
  default:
    DEV: 'fatca-scm-linux'

stages:
- stage: Build
  displayName: Build Service Package
  jobs:
  - job: PackageAndPublishArtifacts
    displayName: Package and Publish Artifacts
    pool:
      name: ${{ parameters.agentPools.DEV }}
    steps:
    - checkout: self
    - checkout: fatca-scm-mcif-service

    - task: CmdLine@2
      displayName: 'Copy Dockerfile'
      inputs:
        script: |
          cp $(System.DefaultWorkingDirectory)/fatca-scm-iac/docker/Dockerfile.mcif-service $(System.DefaultWorkingDirectory)/fatca-scm-mcif-service/
          ls -al $(System.DefaultWorkingDirectory)/fatca-scm-mcif-service/

    - task: CmdLine@2
      displayName: 'Display source branch info and variables'
      inputs:
        script: |
          echo SourceBranch: $(Build.SourceBranch)
          echo SourceBranchName: $(Build.SourceBranchName)
          echo Source is-tag: $(is-tag)
          echo Resource repo tag-filter: $(tag-filter)
          echo ref: $(fatca-scm-mcif-service.ref)
          echo image-tag: $(image-tag)
          echo build repo name: $(Build.Repository.Name)

    - task: CmdLine@2
      displayName: 'Set build id tag for branch builds'
      condition: and(eq(variables['is-tag'], 'false'), eq(variables['tag-filter'], 'false'))
      inputs:
        script: |
          echo "##vso[task.setvariable variable=image-tag]$(Build.BuildId)"
          echo image-tag: $(image-tag)

    - task: CmdLine@2
      displayName: 'Create git-tag file'
      inputs:
        script: |
          echo $(image-tag) > $(System.DefaultWorkingDirectory)/git-tag

    - task: Docker@2
      displayName: 'Docker Login'
      inputs:
        command: login
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        containerRegistry: '$(ACR_SERVICE_CONNECTION)'
        repository: '$(REPO)'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)/fatca-scm-mcif-service/Dockerfile.mcif-service'
        tags: |
          $(image-tag)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish docker-compose artifact'
      inputs:
        PathToPublish: '$(System.DefaultWorkingDirectory)/fatca-scm-iac/docker/docker-compose.yml'
        ArtifactName: 'docker-compose.yml'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish git-tag artifact'
      inputs:
        PathToPublish: '$(System.DefaultWorkingDirectory)/git-tag'
        ArtifactName: 'git-tag'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish scripts artifact'
      inputs:
        PathToPublish: '$(System.DefaultWorkingDirectory)/fatca-scm-iac/scripts'
        ArtifactName: 'scripts'
        publishLocation: 'Container'

- ${{ each env in parameters.env }}:
  - stage: Release${{ env }}
    displayName: Release ${{ env }}
    dependsOn: Build
    pool:
      name: ${{ parameters.agentPools[env] }}
    jobs:
    - deployment: ${{ env }}
      displayName: Deploy ${{ env }}
      environment: ${{ parameters.serviceName }}-${{ env }}
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: docker-compose.yml

            - download: current
              artifact: git-tag

            - download: current
              artifact: scripts

            - task: Docker@2
              displayName: 'Docker Login'
              inputs:
                containerRegistry: '$(ACR_SERVICE_CONNECTION)'
                command: login

            - task: Bash@3
              displayName: 'Docker Swarm Deploy'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/scripts/${{ parameters.scriptFiles[env] }}'
              env:
                CMT_CLIENT_SECRET: $(CMT_CLIENT_SECRET)